-- SQL code for Supabase SQL Editor
-- This sets up profiles and prompts tables for a live Marketplace

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  username TEXT UNIQUE,
  bio TEXT,
  role TEXT DEFAULT 'user',
  avatar_url TEXT,
  credits INTEGER DEFAULT 120,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Prompts Table
CREATE TABLE IF NOT EXISTS public.prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  model TEXT,
  price INTEGER DEFAULT 0,
  fiat_price TEXT,
  rating DECIMAL(3, 1) DEFAULT 0.0,
  likes INTEGER DEFAULT 0,
  downloads INTEGER DEFAULT 0,
  reliability TEXT,
  reliability_type TEXT DEFAULT 'emerald',
  description TEXT,
  image_url TEXT,
  creator_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Prompts are viewable by everyone." ON public.prompts;
CREATE POLICY "Prompts are viewable by everyone." ON public.prompts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create prompts." ON public.prompts;
CREATE POLICY "Authenticated users can create prompts." ON public.prompts 
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Users can update their own prompts." ON public.prompts;
CREATE POLICY "Users can update their own prompts." ON public.prompts 
  FOR UPDATE USING (auth.uid() = creator_id);

DROP POLICY IF EXISTS "Users can delete their own prompts." ON public.prompts;
CREATE POLICY "Users can delete their own prompts." ON public.prompts 
  FOR DELETE USING (auth.uid() = creator_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    CASE 
      WHEN new.email = 'avanishtripathiavanish79921170@gmail.com' THEN 'admin'
      ELSE 'user'
    END
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


INSERT INTO public.prompts (title, category, model, price, fiat_price, rating, likes, downloads, reliability, reliability_type, description, image_url)
VALUES 
('Hyper-Realistic Cyberpunk Portrait', 'Midjourney', 'MIDJOURNEY V8', 15, '$12.99', 4.8, '1.2k', '840', '98% Reliability', 'emerald', 'Highly detailed prompt for photorealistic architectural glass and neon elements in a cyberpunk setting.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0gEfY77P8og-t9s-StwLL50G1Kdh_qBP-RXyRh2V3hm5l4M_rCqeDgSYVJK3EqbyEuQlMxAF69HBjmhWJxSR-XyQEENOTir16rTcei3IQn4dGAxGn7QWLFHTXU9exp_az796KuzdNKlOjluXlFkacWLBT1D36MOjmVnMcIDrdyktN52HsUQho69MKXlCb2FAnQaB8s_5tclye_LIYnjaokIGZsXylVvOnbDsBPx9xmpgGdC-7NALHK42h60DgC6wFOdaoV3o1fNo'),
('Minimalist Architectural Render', 'Architecture', 'STABLE DIFFUSION 3', 12, '$9.99', 4.5, '950', '420', '95% Reliability', 'emerald', 'Clean and modern minimalist architectural visualization with glass and concrete textures.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCYEC-sCe_gJmifDnY0EaBrToNnVey3Ab9bt46kjYSRJWR01i8Ztn3Nef80uApuD1My_rd2_QW0HXM4v9gWk3LSUHJQnXy4ZCAf59uvaQvFvzE733SJw6qzhbncq3eMoEEfGnJk2XvYfwPaI2f0vQ-rJEBUOh6N00Mn9Xv59YyV4FPs7LhfKZytFE_VhnXrg3BwDEo-TXZY3JQ-CD3W3wkHlUV9tFObTOE0jeQjOIaYUC4UqvhWVYsAAGxaw4f4QrknNhMx1j9Yrj8'),
('Strategic Business Logic Agent', 'GPT-4', 'GPT-5 TURBO', 25, '$24.99', 4.9, '2.5k', '1.8k', '100% Reliable', 'blue', 'Advanced logical reasoning prompt for business strategy and complex data analysis.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuALrfzOAW8Q4zK5GkcrvbDnTWc4_UwZgVjmgFEQp_srS6qTjyd8JhcvwgjfpuAUZKzUIFqCSY5CZnul2XVbJQ9laMK0bH-2tgjEGNu6gzZLszPnOI7PkZeYJhIreXWivsZWxA3_3023sMjqvDEJv2lm03P7su92XdDa_DWmUacOPoTaMHIUrW3A_29Mq3nQYNNxW74BlN-eOtu2KLgMdKngbcscu8on7EdX2GTgGFfvsWiGXaqPy-f5h7I2RcB81j_fhkIgJO3Lq2U'),
('Organic Liquid Motion Background', 'Abstract', 'DALL-E 3', 10, '$7.99', 4.2, '800', '310', '92% Reliability', 'emerald', 'Smooth flowing liquid textures for high-end background visualizations and motion graphics.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvRZSLWDavVwIcq5GlOseofZmkO62eJ9rusYAn2NNFwAOoMIYE-1Nq1v8eqQd9EBrHsYMp5QZ7antTAnkw4bTxccogwuBOX1TO0D2-koVoml2FAglDwjfSvthGTd0wqae5e8d1kb7DN1VXhbcem9v0Ae8g9Ven8TE6O-WorFE05IRpwzsGzoXSw1ERB-Ytj_LygHPDaV1nbRlHQENogmgRws9z2YaQapJscJNUiON4En9AmTnJYdnvB32OOMODSQjVpx5MO2vFroY'),
('8K Nature Forest Photography', 'Nature', 'MIDJOURNEY V7', 18, '$15.99', 4.7, '1.4k', '920', '97% Reliability', 'emerald', 'Incredible depth and realistic forest lighting captured in amazing 8K resolution.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDI987ybQdbxwPydnrprUfqA62O7YApVvRSJ7TCft7JoahgzuLRlr-wXCzGOxKM-23bF3DYoXNDtxBqBsbQ16ws1p6UDRj2nlIhnqYh0zxmHfloczbCQWbAQzepllwO4irXJ7SgGMRlKKrWqoyNunVhxXvuoGwhaxzL-9J6qdnlzRh0t4pLWEVO-bzmsocuFqSbO7QWAHJLxiZ7Doh_g7MroooFZpLBRkemaCRNDDKViwfOA0w771JCETACLhpG1oUj6xdRzgfuDCU');

-- 3. Folders Table ( neural vault system )
CREATE TABLE IF NOT EXISTS public.folders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  icon TEXT DEFAULT 'folder',
  color TEXT DEFAULT 'bg-slate-900',
  asset_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for Folders
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own folders." ON public.folders;
CREATE POLICY "Users can view their own folders." ON public.folders 
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own folders." ON public.folders;
CREATE POLICY "Users can insert their own folders." ON public.folders 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own folders." ON public.folders;
CREATE POLICY "Users can update their own folders." ON public.folders 
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own folders." ON public.folders;
CREATE POLICY "Users can delete their own folders." ON public.folders 
  FOR DELETE USING (auth.uid() = user_id);
